### ISSUE TITLE
Socket Connection Gets Destroyed

### ISSUE THREAD

**Issue by GGameGit** [MidLevel/MLAPI.ServerList#3]
Hey TwoPenPvP,

I started to use MLAPI Network and thats how i found ServiceList. Thank you for creating it :)
Now i am facing an issue with ServiceList. Mongodb and the server side code are both running and i can successfully store and retrieve data in unity from mongodb. But only for 20 seconds. 
The reason for this is the LastPingTime. The Client Code never sends an MessageType.ServerAlive. And the mongo query only takes value, where the LastPingTime is not older than 20 seconds. 

Why does my client not send MessageType.ServerAlive ?
My socket connection gets destroyed, before i can send MessageType.ServerAlive. And then if unity tries to use the destroyed socket, i get the following error message:

ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
System.Net.Sockets.Socket.ThrowIfDisposedAndClosed () (at <ae22a4e8f83c41d69684ae>:0)
System.Net.Sockets.Socket.Send (System.Byte[] buffer, System.Int32 offset, System.Int32 size, System.Net.Sockets.SocketFlags socketFlags, System.Net.Sockets.SocketError& errorCode) (at <ae22a4e8f83c41d69684ae>:0)
System.Net.Sockets.Socket.Send (System.Byte[] buffer, System.Int32 offset, System.Int32 size, System.Net.Sockets.SocketFlags socketFlags) (at <ae22a4e8f83c41d69684ae>:0)
MLAPI.ServerList.Client.ServerConnection.<StartAdvertisment>b__11_0 () (at Assets/Scripts/MLAPI Lobby/MLAPI.ServerList.Client/ServerConnection.cs:582)
System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) (at <567df3e0919241ba98db88bec>:0)
System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <567df3e0919241ba98db88bec>:0)
System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <567df3e0919241ba98db88bec>:0)
System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) (at <567df3e0919241ba98db88bec>:0)
System.Threading.ThreadHelper.ThreadStart () (at <567df3e0919241ba98db88bec>:0)
UnityEngine.UnhandledExceptionHandler:<RegisterUECatcher>m__0(Object, UnhandledExceptionEventArgs) (at /home/builduser/buildslave/unity/build/Runtime/Export/Scripting/UnhandledExceptionHandler.bindings.cs:46)

I debugged the code and found out, that my socket connection is fine, as long as the server does not send the Message.RegisterAck (aka the RegisteredGUID). As soon as the client gets the Message.RegisterAck, the socket connection gets destroyed.
With some testing i dount out, if a comment out the Message.RegisterAck on the ServerSide, the Socket connection does never get destroyed, but the client still not sends MessageType.ServerAlive, because without Message.RegisterAck 
the RegisteredGUID on client side is missing and the client cant send the MessageType.ServerAlive again. 

Here is a little illustrate of MLAPI.Serverlist.Client inside ServerConnection.cs from 534 to better understand
`
 new Thread(() =>
            {
                while (isAdvertising)
                {
            	    //registerGuid is null and client.Client.Connected == true. --> client is waiting for RegisterAck to get the registerGuid
                    Thread.Sleep(10000);
		     
                    if (registerGuid != null && isAdvertising)
                    {
                        //RegisterAck came in. registerGuid is NOT null anymore, but now the client.Client.Connected == false
                        ...
                        client.Client.Send(MessageType.ServerAlive); //fails because of lost connection
`
   
I cant explain this behaviour. Do you have an idea ? 
Maybe my unity cant handle more then one thread and i need to change some settings. 
Or i integrated the client code wrong in unity. i just copy and pasted the client folder code inside unity. maybe i should have integrated the code as an dll.

**Comment by Myxcil** [comment]
The using(...) construct disposes the TcpClient too. (ServerConnection.cs, 70). I just removed the using and added a reader.Close() at the end.
Source: https://stackoverflow.com/questions/38081170/tcpclient-getting-disposed-automatically

**Comment by Myxcil** [comment]
Edit: it seems that Close also kills the socket, so I removed it and moved the BinaryReader ctor outside the while loop.

**Comment by GGameGit** [comment]
Thanks for your feedback! I only found one way to make the ping working.

Instead of this:
 else if (messageType == (byte)MessageType.RegisterAck)
                                {
                                    registerGuid = new Guid(reader.ReadString());
                                    bool success = reader.ReadBoolean();


adding a while loop:
 else if (messageType == (byte)MessageType.RegisterAck)
                                {
                                    registerGuid = new Guid(reader.ReadString());
                                    bool success = reader.ReadBoolean();
                                    while(isadvertising){} //loop basically for ever 


But with this solution, i think my reader is always stuck on the first message (did not test it yet). So your solution with removing the using from Binary reader sounds more promising :) i will try it tomorrow.

**Comment by TwoTenPvP** [comment]
There is a constructor parameter to not dispose the underlying stream when disposing the binary reader / writer. That should be used.

**Comment by Myxcil** [comment]
The referenced BinaryReader from NET Framework 2.0 doesn't have this ctor.

**Comment by TwoTenPvP** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.io.binarywriter.-ctor?view=netcore-3.1#System_IO_BinaryWriter__ctor_System_IO_Stream_System_Text_Encoding_System_Boolean_

**Comment by Myxcil** [comment]
You may be right here, but if you look closely you see that you have referenced "netcore-3.1". I'm talking about the NET Framework 2.0 reference that is used in ServerList
https://docs.microsoft.com/en-us/dotnet/api/system.io.binarywriter.-ctor?view=netframework-2.0#System_IO_BinaryWriter__ctor_System_IO_Stream_System_Text_Encoding_System_Boolean

**Comment by GGameGit** [comment]
Thanks TwoTenPvp for solving the issue.

Just for the other people who read this:

BinaryReader(Stream, Encoding, Boolean) | Initializes a new instance of the BinaryReader class based on the specified stream and character encoding, and optionally leaves the stream open.

Inside Serverconnection -> Method public void Connect(string host, int port)
-----
From:
 using (BinaryReader reader = new BinaryReader(client.GetStream(), Encoding.UTF8))
To:
 using (BinaryReader reader = new BinaryReader(client.GetStream(), Encoding.UTF8,true))
